# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.dates
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=utils.dates.utcnow)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
