# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170408_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
