# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.dates
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment', '0001_initial'),
        ('customer', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=utils.dates.utcnow)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('minimum_investment_size', models.IntegerField(blank=True)),
                ('maximum_investment_size', models.IntegerField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer.Customer')),
                ('investment_type_preferences', models.ManyToManyField(blank=True, related_name='interested_contacts', to='investment.InvestmentType')),
                ('region_preferences', models.ManyToManyField(blank=True, related_name='interested_contacts', to='region.Region')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=utils.dates.utcnow)),
                ('is_active', models.BooleanField(default=True)),
                ('begin_date', models.DateField()),
                ('frequency', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='contact.Contact')),
            ],
        ),
    ]
