# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='maximum_investment_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='minimum_investment_size',
            field=models.IntegerField(blank=True),
        ),
    ]
