# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('contact', '0002_auto_20170312_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='contact.Contact'),
        ),
    ]
