# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170312_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_by',
            new_name='creator',
        ),
    ]
