# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20170312_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
    ]
