# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.dates
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20170323_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=utils.dates.utcnow)),
                ('correspondence_type', models.TextField(blank=True)),
                ('item_id', models.TextField(blank=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondences', to='contact.Contact')),
            ],
        ),
    ]
