# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
