# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20170412_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondence',
            options={'ordering': ('-date',)},
        ),
    ]
