# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 15:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import utils.dates
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_auto_20170408_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=utils.dates.utcnow)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='TeamEventCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=utils.dates.utcnow)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teamevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.TeamEventCategory'),
        ),
        migrations.AddField(
            model_name='teamevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='teamevent',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customer.Team'),
        ),
    ]
