# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teameventcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Team event categories'},
        ),
    ]
