# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import utils.dates
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=utils.dates.utcnow)),
                ('company', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('date_published', models.DateTimeField()),
            ],
        ),
    ]
