# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='link',
            new_name='url',
        ),
    ]
